[tool.ruff]
target-version = "py311"
line-length = 100

[tool.ruff.lint]
select = ["E","F","I","UP","B","W","D","PL","C90"]
ignore = ["D100","D104"]  # pas aan op jouw docstringbeleid

[tool.ruff.format]
quote-style = "double"
