env:
  COG_BASE: "."          # was: cogs

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      any_changed: ${{ steps.set-matrix.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set-matrix
        run: |
          set -e

          # Een "cog" definiëren we als een map met óf __init__.py óf info.json
          list_cogs() {
            find "${COG_BASE}" -maxdepth 1 -mindepth 1 -type d \
              \( -exec test -f "{}/__init__.py" \; -o -exec test -f "{}/info.json" \; \) \
              -print | sort
          }

          BASE_REF="${{ github.event.pull_request.base.sha || github.event.before }}"
          HEAD_REF="${{ github.sha }}"

          # Zoek gewijzigde paden binnen de basis (alleen mappen)
          CHANGED=$(git diff --name-only "$BASE_REF" "$HEAD_REF" -- "${COG_BASE}/" \
            | awk -F/ '{print $1}' | sort -u)

          # Filter CHANGED tot echte cog-mappen
          CHANGED_COGS=""
          for d in $CHANGED; do
            if [ -d "$d" ] && { [ -f "$d/__init__.py" ] || [ -f "$d/info.json" ]; }; then
              CHANGED_COGS="$CHANGED_COGS
$d"
            fi
          done
          CHANGED_COGS=$(echo "$CHANGED_COGS" | sed '/^$/d' || true)

          if [ -z "$CHANGED_COGS" ]; then
            echo "Geen specifieke cogs gewijzigd; val terug op alle cogs."
            ALL=$(list_cogs)
            if [ -z "$ALL" ]; then
              echo "::error::Geen cogs gevonden in ${COG_BASE}/ (zoek naar mappen met __init__.py of info.json)"
              exit 1
            fi
            arr=$(printf '%s\n' $ALL | jq -R . | jq -s .)
            echo "matrix={\"cog_path\":$arr}" >> $GITHUB_OUTPUT
            echo "any_changed=false" >> $GITHUB_OUTPUT
          else
            arr=$(printf '%s\n' $CHANGED_COGS | jq -R . | jq -s .)
            echo "matrix={\"cog_path\":$arr}" >> $GITHUB_OUTPUT
            echo "any_changed=true" >> $GITHUB_OUTPUT
          fi
