"""
Discord formatting for MissionChief possible missions.
"""

from __future__ import annotations

from typing import Any

import discord

from .mappings import (
    EQUIPMENT,
    TRAININGS,
    format_field_name,
    get_building_name,
    get_extension_name,
    get_vehicle_name,
)
from .mission_fetcher import MissionFetcher


class MissionFormatter:
    """Build compact Discord output for a possible mission."""

    FORMAT_VERSION = "possible-missions-v3"
    MARKER_PREFIX = "MissionChief Possible Mission"

    @classmethod
    def build_content(cls, mission_data: dict[str, Any]) -> str:
        mission_key = MissionFetcher.mission_key(mission_data)
        return f"{cls.MARKER_PREFIX}: `{mission_key}`"

    @classmethod
    def build_embed(cls, mission_data: dict[str, Any]) -> discord.Embed:
        mission_key = MissionFetcher.mission_key(mission_data)
        mission_name = MissionFetcher.mission_name(mission_data)
        detail_url = MissionFetcher.detail_url(mission_data)

        embed = discord.Embed(
            title=cls.truncate(f"{mission_key} - {mission_name}", 256),
            url=detail_url,
            color=discord.Color.dark_blue(),
        )
        embed.add_field(name="Average Credits", value=cls.average_credits(mission_data), inline=True)
        embed.add_field(name="Mission Types", value=cls.categories(mission_data), inline=True)
        embed.add_field(name="Generated By", value=cls.generated_by(mission_data), inline=True)

        unlocks = cls.unlocks(mission_data)
        if unlocks:
            embed.add_field(name="Unlock Requirements", value=unlocks, inline=False)

        requirements = cls.requirements(mission_data)
        if requirements:
            embed.add_field(name="Vehicle / Equipment Requirements", value=requirements, inline=False)

        medical = cls.medical_and_prisoner_info(mission_data)
        if medical:
            embed.add_field(name="Patients / Prisoners", value=medical, inline=False)

        poi = cls.poi(mission_data)
        if poi:
            embed.add_field(name="POI", value=poi, inline=False)

        other_info = cls.other_information(mission_data)
        if other_info:
            embed.add_field(name="Other Information", value=other_info, inline=False)

        embed.set_footer(text=f"Mission ID: {mission_key} | Source: MissionChief Possible Missions")
        return embed

    @classmethod
    def thread_title(cls, mission_data: dict[str, Any]) -> str:
        mission_key = MissionFetcher.mission_key(mission_data)
        mission_name = MissionFetcher.mission_name(mission_data)
        return cls.truncate(f"[{mission_key}] {mission_name}", 100)

    @staticmethod
    def average_credits(mission_data: dict[str, Any]) -> str:
        credits = mission_data.get("average_credits") or 0
        try:
            return f"{int(credits):,}"
        except (TypeError, ValueError):
            return str(credits)

    @staticmethod
    def categories(mission_data: dict[str, Any]) -> str:
        categories = mission_data.get("mission_categories", []) or []
        if not categories:
            return "Unknown"
        return MissionFormatter.truncate(
            ", ".join(format_field_name(str(category)) for category in categories),
            1024,
        )

    @staticmethod
    def generated_by(mission_data: dict[str, Any]) -> str:
        generated_by = mission_data.get("generated_by")
        if generated_by:
            return str(generated_by)

        main_building = (mission_data.get("prerequisites") or {}).get("main_building")
        if main_building == -1:
            return "Any station"
        if main_building not in (None, ""):
            return get_building_name(main_building)
        return "Unknown"

    @classmethod
    def unlocks(cls, mission_data: dict[str, Any]) -> str:
        prerequisites = mission_data.get("prerequisites", {}) or {}
        lines: list[str] = []
        for key, value in prerequisites.items():
            if key == "main_building" or cls.empty(value):
                continue
            if isinstance(value, dict):
                continue
            label = cls.prerequisite_name(str(key))
            lines.append(f"- {value} {label}")
        return cls.truncate_lines(lines, 1024)

    @classmethod
    def requirements(cls, mission_data: dict[str, Any]) -> str:
        requirements = mission_data.get("requirements", {}) or {}
        lines: list[str] = []
        trainings: list[str] = []

        for key, value in requirements.items():
            if cls.empty(value):
                continue
            if isinstance(value, dict):
                for training_key, training_count in value.items():
                    if cls.empty(training_count):
                        continue
                    training_name = TRAININGS.get(str(training_key), format_field_name(str(training_key)))
                    trainings.append(f"- {training_count} {training_name}")
                continue

            label = get_vehicle_name(str(key))
            if str(key) in EQUIPMENT or "equipment" in str(key).casefold():
                label = EQUIPMENT.get(str(key), label)
            lines.append(f"- {cls.format_requirement_value(value, label)}")

        output: list[str] = []
        if trainings:
            output.append("Training:")
            output.extend(trainings)
        if lines:
            if output:
                output.append("")
            output.extend(lines)

        return cls.truncate_lines(output, 1024)

    @classmethod
    def medical_and_prisoner_info(cls, mission_data: dict[str, Any]) -> str:
        additional = mission_data.get("additional", {}) or {}
        chances = mission_data.get("chances", {}) or {}
        lines: list[str] = []

        patients = additional.get("possible_patient") or 0
        if patients:
            lines.append(f"- Patients: up to {patients}")
            transport = chances.get("patient_transport")
            if transport:
                lines.append(f"- Patient transport chance: {transport}%")
            specializations = additional.get("patient_specialization_captions") or []
            if specializations:
                lines.append(f"- Specializations: {', '.join(map(str, specializations))}")

        min_prisoners = additional.get("min_possible_prisoners") or 0
        max_prisoners = additional.get("max_possible_prisoners") or 0
        prisoners = additional.get("possible_prisoner_count") or 0
        if min_prisoners or max_prisoners:
            if min_prisoners == max_prisoners:
                lines.append(f"- Prisoners: {min_prisoners}")
            else:
                lines.append(f"- Prisoners: {min_prisoners}-{max_prisoners}")
        elif prisoners:
            lines.append(f"- Prisoners: up to {prisoners}")

        return cls.truncate_lines(lines, 1024)

    @staticmethod
    def poi(mission_data: dict[str, Any]) -> str:
        places = mission_data.get("place_array") or []
        if not places and mission_data.get("place"):
            places = [mission_data["place"]]
        if not places:
            return ""
        return MissionFormatter.truncate(", ".join(map(str, places)), 1024)

    @classmethod
    def other_information(cls, mission_data: dict[str, Any]) -> str:
        additional = mission_data.get("additional", {}) or {}
        lines: list[str] = []

        expansion_names = additional.get("expansion_mission_names") or []
        expansion_ids = additional.get("expansion_missions_ids") or []
        if expansion_names:
            lines.append(f"- Expandable Missions: {', '.join(map(str, expansion_names))}")
        elif expansion_ids:
            lines.append(f"- Expandable Missions: {', '.join(f'Mission {value}' for value in expansion_ids)}")

        crashed_car_min = additional.get("possible_crashed_car_min")
        crashed_car_max = additional.get("possible_crashed_car_max")
        if crashed_car_min not in (None, ""):
            lines.append(f"- Minimum cars to tow: {crashed_car_min}")
        if crashed_car_max not in (None, ""):
            lines.append(f"- Maximum cars to tow: {crashed_car_max}")

        if mission_data.get("additive_overlays"):
            lines.append(f"- Mission Variation: {MissionFetcher.mission_name(mission_data)}")

        return cls.truncate_lines(lines, 1024)

    @staticmethod
    def prerequisite_name(key: str) -> str:
        if key.endswith("_extension") or key.endswith("_count") or key in {"tow_trucks"}:
            return get_extension_name(key).replace(" Extension", "")
        return format_field_name(key)

    @staticmethod
    def format_requirement_value(value: Any, label: str) -> str:
        text = str(value)
        if "oneof" not in text.casefold():
            return f"{value} {label}"

        return text.replace("oneof", "one of").replace(" or ", " OR ")

    @staticmethod
    def empty(value: Any) -> bool:
        return value in (None, "", 0, [], {})

    @staticmethod
    def truncate(value: str, limit: int) -> str:
        if len(value) <= limit:
            return value
        return value[: limit - 3].rstrip() + "..."

    @staticmethod
    def truncate_lines(lines: list[str], limit: int) -> str:
        output = ""
        remaining = len(lines)
        for line in lines:
            addition = f"\n{line}" if output else line
            if len(output) + len(addition) > limit:
                suffix = f"\n... and {remaining} more"
                return MissionFormatter.truncate(output + suffix, limit)
            output += addition
            remaining -= 1
        return output
